---
abstract: 'Sets up L<Log::Deep> for Catalyst logging'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  File::Spec: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-LogDeep
provides:
  Catalyst::Plugin::LogDeep:
    file: lib/Catalyst/Plugin/LogDeep.pm
    version: v0.0.3
recommends:
  Pod::Coverage: 0
  Test::Kwalitee: 0
  Test::Perl::Critic: 0
  Test::Spelling: 0
requires:
  Catalyst: 5.7
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Class::C3::Adopt::NEXT: 0
  Log::Deep: 0.000006
  parent: 0
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Catalyst-Plugin-LogDeep
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/Catalyst-Plugin-LogDeep.git
version: v0.0.3
